-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "task" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "columnId" integer NOT NULL,
    "projectId" integer NOT NULL,
    "title" varchar(300) NOT NULL,
    "description" varchar(4000) NOT NULL,
    "status" varchar(30) NOT NULL,
    "priority" varchar(20) NOT NULL,
    "position" integer NOT NULL,
    "dueDate" varchar(40) NOT NULL,
    "createdById" integer NOT NULL,
    "createdAt" timestamptz NOT NULL,
    "updatedAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
