-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "board" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "projectId" integer NOT NULL,
    "name" varchar(150) NOT NULL,
    "position" integer NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "column" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "boardId" integer NOT NULL,
    "name" varchar(150) NOT NULL,
    "position" integer NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "project" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "workspaceId" integer NOT NULL,
    "name" varchar(150) NOT NULL,
    "description" varchar(2000) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
