-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "activity" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "projectId" integer NOT NULL,
    "actorId" integer NOT NULL,
    "type" varchar(50) NOT NULL,
    "payload" varchar(1000) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "comment" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskId" integer NOT NULL,
    "authorId" integer NOT NULL,
    "body" varchar(4000) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
