-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" varchar(120) NOT NULL,
    "passwordHash" varchar(255) NOT NULL,
    "name" varchar(120) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "workspace" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar(150) NOT NULL,
    "ownerId" integer NOT NULL,
    "createdAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "workspace_member" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "workspaceId" integer NOT NULL,
    "userId" integer NOT NULL,
    "role" varchar(20) NOT NULL,
    PRIMARY KEY ("id")
);
