-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "label" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "workspaceId" integer NOT NULL,
    "name" varchar(80) NOT NULL,
    "color" varchar(20) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "task_assignee" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskId" integer NOT NULL,
    "userId" integer NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "task_label" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskId" integer NOT NULL,
    "labelId" integer NOT NULL,
    PRIMARY KEY ("id")
);
