-- Generated by `jwc migrate new`. Do not edit.
-- down of 1781605087_port_to_1_0
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 9 · destructive ──
DROP TABLE public.activity;
DROP TABLE public.comment;
DROP TABLE public.task_assignee;
DROP TABLE public.task_label;
DROP TABLE public.label;
DROP TABLE public.task;
DROP TABLE public."column";
DROP TABLE public.board;
DROP TABLE public.project;
DROP TABLE public.workspace_member;
DROP TABLE public.workspace;
DROP TABLE public."user";

COMMIT;
