-- Generated by jwc (incremental diff)
ALTER TABLE "activity" ALTER COLUMN "payload" TYPE jsonb USING "payload"::jsonb;
-- schema_diff honours `unique` only on a fresh CREATE TABLE, not as an
-- incremental ALTER, so the UNIQUE add for the now-`unique` User.email was not
-- emitted (PAIN_LOG2). Added by hand so the existing schema picks it up too.
ALTER TABLE "user" ADD CONSTRAINT "user_email_key" UNIQUE ("email");
