-- Generated by `jwc migrate new`. Do not edit.
-- 1781605087_port_to_1_0
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 1 · schemas and types ──
CREATE SCHEMA IF NOT EXISTS public;

-- ── 2 · tables and columns ──
CREATE TABLE public.activity (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "projectId" integer NOT NULL,
    "actorId" integer NOT NULL,
    type varchar(50) NOT NULL,
    payload jsonb NOT NULL,
    "createdAt" timestamptz NOT NULL,
    CONSTRAINT pk_activity PRIMARY KEY (id)
);
CREATE TABLE public.board (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "projectId" integer NOT NULL,
    name varchar(150) NOT NULL,
    position integer NOT NULL,
    CONSTRAINT pk_board PRIMARY KEY (id)
);
CREATE TABLE public."column" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "boardId" integer NOT NULL,
    name varchar(150) NOT NULL,
    position integer NOT NULL,
    CONSTRAINT pk_column PRIMARY KEY (id)
);
CREATE TABLE public.comment (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskId" integer NOT NULL,
    "authorId" integer NOT NULL,
    body varchar(4000) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);
CREATE TABLE public.label (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "workspaceId" integer NOT NULL,
    name varchar(80) NOT NULL,
    color varchar(20) NOT NULL,
    CONSTRAINT pk_label PRIMARY KEY (id)
);
CREATE TABLE public.project (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "workspaceId" integer NOT NULL,
    name varchar(150) NOT NULL,
    description varchar(2000) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);
CREATE TABLE public.task (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "columnId" integer NOT NULL,
    "projectId" integer NOT NULL,
    title varchar(300) NOT NULL,
    description varchar(4000) NOT NULL,
    status varchar(30) NOT NULL,
    priority varchar(20) NOT NULL,
    position integer NOT NULL,
    "dueDate" timestamptz,
    "createdById" integer NOT NULL,
    "createdAt" timestamptz NOT NULL,
    "updatedAt" timestamptz NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id)
);
CREATE TABLE public.task_assignee (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskId" integer NOT NULL,
    "userId" integer NOT NULL,
    CONSTRAINT pk_task_assignee PRIMARY KEY (id),
    CONSTRAINT "uq_task_assignee__taskId_userId" UNIQUE ("taskId", "userId")
);
CREATE TABLE public.task_label (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskId" integer NOT NULL,
    "labelId" integer NOT NULL,
    CONSTRAINT pk_task_label PRIMARY KEY (id),
    CONSTRAINT "uq_task_label__taskId_labelId" UNIQUE ("taskId", "labelId")
);
CREATE TABLE public."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(120) NOT NULL,
    "passwordHash" varchar(255) NOT NULL,
    name varchar(120) NOT NULL,
    "createdAt" timestamptz NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user__email UNIQUE (email)
);
CREATE TABLE public.workspace (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(150) NOT NULL,
    "ownerId" integer NOT NULL,
    "createdAt" timestamptz NOT NULL,
    CONSTRAINT pk_workspace PRIMARY KEY (id)
);
CREATE TABLE public.workspace_member (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "workspaceId" integer NOT NULL,
    "userId" integer NOT NULL,
    role varchar(20) NOT NULL,
    CONSTRAINT pk_workspace_member PRIMARY KEY (id),
    CONSTRAINT "uq_workspace_member__workspaceId_userId" UNIQUE ("workspaceId", "userId")
);

-- ── 3 · data ──
-- jwc:data 1781605087_port_to_1_0
-- A `1781605087_port_to_1_0.data.sql` sidecar, if present, is applied here
-- (migrations.md §7.2). It is hand-written and never generated.

-- ── 4 · constraints ──
ALTER TABLE public.activity ADD CONSTRAINT "fk_activity__actorId"
    FOREIGN KEY ("actorId") REFERENCES public."user" (id)
    ON DELETE CASCADE;
ALTER TABLE public.activity ADD CONSTRAINT "fk_activity__projectId"
    FOREIGN KEY ("projectId") REFERENCES public.project (id)
    ON DELETE CASCADE;
ALTER TABLE public.board ADD CONSTRAINT "fk_board__projectId"
    FOREIGN KEY ("projectId") REFERENCES public.project (id)
    ON DELETE CASCADE;
ALTER TABLE public."column" ADD CONSTRAINT "fk_column__boardId"
    FOREIGN KEY ("boardId") REFERENCES public.board (id)
    ON DELETE CASCADE;
ALTER TABLE public.comment ADD CONSTRAINT "fk_comment__authorId"
    FOREIGN KEY ("authorId") REFERENCES public."user" (id)
    ON DELETE CASCADE;
ALTER TABLE public.comment ADD CONSTRAINT "fk_comment__taskId"
    FOREIGN KEY ("taskId") REFERENCES public.task (id)
    ON DELETE CASCADE;
ALTER TABLE public.label ADD CONSTRAINT "fk_label__workspaceId"
    FOREIGN KEY ("workspaceId") REFERENCES public.workspace (id)
    ON DELETE CASCADE;
ALTER TABLE public.project ADD CONSTRAINT "fk_project__workspaceId"
    FOREIGN KEY ("workspaceId") REFERENCES public.workspace (id)
    ON DELETE CASCADE;
ALTER TABLE public.task ADD CONSTRAINT "fk_task__columnId"
    FOREIGN KEY ("columnId") REFERENCES public."column" (id)
    ON DELETE CASCADE;
ALTER TABLE public.task ADD CONSTRAINT "fk_task__createdById"
    FOREIGN KEY ("createdById") REFERENCES public."user" (id);
ALTER TABLE public.task ADD CONSTRAINT "fk_task__projectId"
    FOREIGN KEY ("projectId") REFERENCES public.project (id)
    ON DELETE CASCADE;
ALTER TABLE public.task_assignee ADD CONSTRAINT "fk_task_assignee__taskId"
    FOREIGN KEY ("taskId") REFERENCES public.task (id)
    ON DELETE CASCADE;
ALTER TABLE public.task_assignee ADD CONSTRAINT "fk_task_assignee__userId"
    FOREIGN KEY ("userId") REFERENCES public."user" (id)
    ON DELETE CASCADE;
ALTER TABLE public.task_label ADD CONSTRAINT "fk_task_label__labelId"
    FOREIGN KEY ("labelId") REFERENCES public.label (id)
    ON DELETE CASCADE;
ALTER TABLE public.task_label ADD CONSTRAINT "fk_task_label__taskId"
    FOREIGN KEY ("taskId") REFERENCES public.task (id)
    ON DELETE CASCADE;
ALTER TABLE public.workspace ADD CONSTRAINT "fk_workspace__ownerId"
    FOREIGN KEY ("ownerId") REFERENCES public."user" (id);
ALTER TABLE public.workspace_member ADD CONSTRAINT "fk_workspace_member__userId"
    FOREIGN KEY ("userId") REFERENCES public."user" (id)
    ON DELETE CASCADE;
ALTER TABLE public.workspace_member ADD CONSTRAINT "fk_workspace_member__workspaceId"
    FOREIGN KEY ("workspaceId") REFERENCES public.workspace (id)
    ON DELETE CASCADE;

-- ── 5 · indexes ──
CREATE INDEX "ix_activity__projectId_createdAt"
    ON public.activity ("projectId", "createdAt");
CREATE INDEX "ix_board__projectId_position"
    ON public.board ("projectId", position);
CREATE INDEX "ix_column__boardId_position"
    ON public."column" ("boardId", position);
CREATE INDEX "ix_comment__taskId_createdAt"
    ON public.comment ("taskId", "createdAt");
CREATE INDEX "ix_label__workspaceId_name"
    ON public.label ("workspaceId", name);
CREATE INDEX "ix_project__workspaceId_createdAt"
    ON public.project ("workspaceId", "createdAt");
CREATE INDEX "ix_task__columnId_position"
    ON public.task ("columnId", position);
CREATE INDEX "ix_task__projectId_position"
    ON public.task ("projectId", position);
CREATE INDEX "ix_user__createdAt"
    ON public."user" ("createdAt");
CREATE INDEX "ix_workspace_member__userId"
    ON public.workspace_member ("userId");

-- ── 7 · comments ──
COMMENT ON TABLE public.activity IS 'Append-only. `payload` is jsonb, so the shape is per-event and the
reader does not have to know it.';
COMMENT ON TABLE public."column" IS '`Columns`, not `Column`: `column` is a reserved word in Postgres and the
physical name is quoted anyway, but the plural also matches every other
table here.';
COMMENT ON COLUMN public.task."projectId" IS 'Denormalised. Every list query is per-project, and carrying the id
here avoids a column → board → project hop on each one. Stable: a
move only ever re-parents within a project, which `TaskService.move`
enforces.';
COMMENT ON TABLE public.task_assignee IS 'Join table: Task ↔ User.';
COMMENT ON TABLE public.task_label IS 'Join table: Task ↔ Label. The pair is unique, which is what makes
`addLabel` idempotent without a read first.';
COMMENT ON TABLE public."user" IS 'Every table and column below carries an `as "…"` override: the physical
names are what the 0.9.x deployment created, and they are not what 1.0
would spell them. See `app.jwc` for why they are kept.
One human identity. Email is the login handle.';
COMMENT ON COLUMN public."user"."passwordHash" IS 'Argon2id. `private` keeps it out of every projection, so a `select`
cannot leak it even by asking (schema.md §3.1).';
COMMENT ON TABLE public.workspace_member IS 'The authorisation table. Every read below a workspace goes through it.';

COMMIT;
